#! /bin/sh

sxhkd &

bspc monitor eDP1 -d I II III IV 
bspc monitor HDMI1 -d V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

feh --bg-scale Pictures/1477443690806.jpg

~/bin/panel &
